/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Swing;

import Model.Book;
import Model.Customer;
import Model.Employee;
import Service.BookService;
import Service.CustomerService;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class EmployeePage extends javax.swing.JFrame {

    HashMap<String, Book> bookMap = new HashMap<>();
    HashSet<Customer> CustomerList = new HashSet<>();
    BookService bookSer = new BookService();
    CustomerService customerService = new CustomerService();
    Login LoginPage = new Login();
    SimpleDateFormat tableDateFormat = new SimpleDateFormat("MMM, yyyy", Locale.ENGLISH);
    EmployeeInfor emIn;

    /**
     * Creates new form CustomerPage
     */
    public EmployeePage(Employee employee) {
        emIn = new EmployeeInfor(employee);
        initComponents();
        setTitle("Employee Page");
        setResizable(true);
        //setSize(WIDTH, );
        //setSize(Toolkit.getDefaultToolkit().getScreenSize());
        displayBook();
        displayCus();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    public void displayBook() {
        bookMap.clear();
        bookMap = bookSer.getBookMap();
        DefaultTableModel model = (DefaultTableModel) JBookTable.getModel();
        model.setRowCount(0); // Xóa các dòng cũ (nếu có)
        for (Book book : bookMap.values()) {
            // (bookID, title,isbn, author, publishDateStr, bookPrice, quantity, type, language);
            model.addRow(new Object[]{book.getBookId(), book.getTitle(), book.getAuthor(), book.getIsbn(), book.getPublishedDate(), book.getQuantity(), book.getType(), book.getPrice()});

        }
    }

    public void displayCus() {
        CustomerList.clear();
        CustomerList = customerService.getCustomerSet();
        DefaultTableModel model1 = (DefaultTableModel) jCusTable.getModel();
        model1.setRowCount(0);
        for (Customer customer : CustomerList) {
            model1.addRow(new Object[]{customer.getId(), customer.getName(), customer.getSSN(), customer.getBirthDate(), customer.getGender(), customer.getPhoneNumber(), customer.getEmail(), customer.getAddress(), customer.getTotalPayment()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextBookID = new javax.swing.JTextField();
        JTitle = new javax.swing.JTextField();
        jTextAuthor = new javax.swing.JTextField();
        jPrice = new javax.swing.JTextField();
        ValueQuantity = new javax.swing.JSpinner();
        jCombolanguage = new javax.swing.JComboBox<>();
        jType = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonAddBook = new javax.swing.JButton();
        jButtonDeleteBook = new javax.swing.JButton();
        jButtonFindBook = new javax.swing.JButton();
        jButtonEditBook = new javax.swing.JButton();
        jTextPublishDate = new javax.swing.JTextField();
        jTextIsBN = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JBookTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextCusID = new javax.swing.JTextField();
        jTextCusName = new javax.swing.JTextField();
        jComboCusGender = new javax.swing.JComboBox<>();
        jFormattedTextPhone = new javax.swing.JFormattedTextField();
        jFormattedTextCusSSN = new javax.swing.JFormattedTextField();
        jTextCusEmail = new javax.swing.JTextField();
        jComboAddress = new javax.swing.JComboBox<>();
        jDateCusdate = new com.toedter.calendar.JDateChooser();
        DELETECUS = new javax.swing.JButton();
        EDITCUS = new javax.swing.JButton();
        FINDCUS = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCusTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EmployeeInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.darkGray, null, null));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("BookID:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Title:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Author:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("PublishDate:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Price:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Quantity:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Type:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Language:");

        ValueQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jCombolanguage.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "English", "Vietnamese", "Japanese", "chinese", " ", " " }));
        jCombolanguage.setSelectedItem("");

        jType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTypeActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setText("BOOK INFORMATION");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jButtonAddBook.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAddBook.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        jButtonAddBook.setText("ADD");
        jButtonAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonAddBookMousePressed(evt);
            }
        });

        jButtonDeleteBook.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDeleteBook.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        jButtonDeleteBook.setText("Delete");
        jButtonDeleteBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonDeleteBookMousePressed(evt);
            }
        });

        jButtonFindBook.setBackground(new java.awt.Color(204, 204, 204));
        jButtonFindBook.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        jButtonFindBook.setText("Find");
        jButtonFindBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonFindBookMousePressed(evt);
            }
        });
        jButtonFindBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindBookActionPerformed(evt);
            }
        });

        jButtonEditBook.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEditBook.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        jButtonEditBook.setText("Edit");
        jButtonEditBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButtonEditBookMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFindBook, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonDeleteBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEditBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(93, 93, 93))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeleteBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFindBook, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTextPublishDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPublishDateActionPerformed(evt);
            }
        });

        jTextIsBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIsBNActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setText("Isbn:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPublishDate))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jCombolanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel22))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextIsBN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                                    .addComponent(jTextAuthor, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(JTitle, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jTextBookID, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(74, 74, 74)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(ValueQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(5, 5, 5))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextBookID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextIsBN, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextPublishDate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ValueQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jCombolanguage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JBookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Book ID ", "Title ", "Author", "ISBN", "PublishDate", "Quantity", "Type", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        JBookTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBookTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(JBookTable);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel6.setText("BOOK LIST");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(jLabel6)))
                .addContainerGap(420, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("BOOK", jPanel3);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("CUSTOMER ID:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("NAME:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("SSN:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setText("DOB:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel18.setText("PHONE:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("GENDER:");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("EMAIL:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("ADDRESS:");

        jComboCusGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        try {
            jFormattedTextPhone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextPhone.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFormattedTextPhone.setText("ex:0775660817");
        jFormattedTextPhone.setToolTipText("ex:0775660817");

        jFormattedTextCusSSN.setToolTipText("SSN 12 Index");

        jComboAddress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "An Giang", "Ba Ria - Vung Tau", "Bac Giang", "Bac Kan", "Bac Lieu", "Bac Ninh", "Ben Tre", "Binh Dinh", "Binh Duong", "Binh Phuoc", "Binh Thuan", "Ca Mau", "Can Tho", "Cao Bang", "Da Nang", "Dak Lak", "Dak Nong", "Dien Bien", "Dong Nai", "Dong Thap", "Gia Lai", "Ha Giang", "Ha Nam", "Ha Noi", "Ha Tinh", "Hai Duong", "Hai Phong", "Hau Giang", "Hoa Binh", "Hung Yen", "Khanh Hoa", "Kien Giang", "Kon Tum", "Lai Chau", "Lam Dong", "Lang Son", "Lao Cai", "Long An", "Nam Dinh", "Nghe An", "Ninh Binh", "Ninh Thuan", "Phu Tho", "Phu Yen", "Quang Binh", "Quang Nam", "Quang Ngai", "Quang Ninh", "Quang Tri", "Soc Trang", "Son La", "Tay Ninh", "Thai Binh", "Thai Nguyen", "Thanh Hoa", "Thua Thien Hue", "Tien Giang", "TP Ho Chi Minh", "Tra Vinh", "Tuyen Quang", "Vinh Long", "Vinh Phuc", "Yen Bai" }));

        jDateCusdate.setDateFormatString("yyyy-MM-dd");
        jDateCusdate.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);

        DELETECUS.setText("DELETE");
        DELETECUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DELETECUSMousePressed(evt);
            }
        });

        EDITCUS.setText("EDIT");
        EDITCUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITCUSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EDITCUSMousePressed(evt);
            }
        });

        FINDCUS.setText("FIND");
        FINDCUS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FINDCUSMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FINDCUSMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jLabel18)
                                .addComponent(jLabel20)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextCusID)
                            .addComponent(jTextCusName)
                            .addComponent(jComboCusGender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jFormattedTextPhone)
                            .addComponent(jFormattedTextCusSSN)
                            .addComponent(jTextCusEmail)
                            .addComponent(jComboAddress, 0, 318, Short.MAX_VALUE)
                            .addComponent(jDateCusdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(DELETECUS, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(EDITCUS, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(FINDCUS, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCusID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCusName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextCusSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateCusdate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboCusGender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCusEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EDITCUS, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(DELETECUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FINDCUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(372, Short.MAX_VALUE))
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel13.setText("CUSTOMER MANAGEMENT");
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jCusTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "SSN", "Birth Date", "Gender", "Phone", "Email", "Address", "total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jCusTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCusTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jCusTable);
        if (jCusTable.getColumnModel().getColumnCount() > 0) {
            jCusTable.getColumnModel().getColumn(0).setResizable(false);
            jCusTable.getColumnModel().getColumn(0).setPreferredWidth(6);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(473, 473, 473)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(404, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("CUSTOMER", jPanel6);

        jPanel8.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EMPLOYEE PAGE");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/log-out-outline-icon.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(20, 20));
        jLabel2.setMinimumSize(new java.awt.Dimension(20, 20));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        EmployeeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/profile_3135715.png"))); // NOI18N
        EmployeeInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EmployeeInfoMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(EmployeeInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 441, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(323, 323, 323)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(EmployeeInfo))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1912, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1530, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        LoginPage.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked


    private void jTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTypeActionPerformed

    private void jButtonFindBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindBookActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButtonFindBookActionPerformed

    private void JBookTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBookTableMouseClicked

        // TODO add your handling code here:
        int row = JBookTable.getSelectedRow();

        jTextBookID.setText(JBookTable.getValueAt(row, 0).toString());
        String id = jTextBookID.getText();
        JTitle.setText(JBookTable.getValueAt(row, 1).toString());
        jTextAuthor.setText(JBookTable.getValueAt(row, 2).toString());
        jTextIsBN.setText(JBookTable.getValueAt(row, 3).toString());
        String dateStr = JBookTable.getValueAt(row, 4).toString();
        jTextPublishDate.setText(dateStr);
        ValueQuantity.setValue(Integer.parseInt(JBookTable.getValueAt(row, 5).toString()));
        jType.setText(JBookTable.getValueAt(row, 6).toString());
        jPrice.setText(JBookTable.getValueAt(row, 7).toString());
        Book book = bookSer.findById(id);
        jCombolanguage.setSelectedItem(book.getLanguage());
    }//GEN-LAST:event_JBookTableMouseClicked

    private void jTextPublishDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPublishDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPublishDateActionPerformed

    private void jCusTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCusTableMouseClicked
        // TODO add your handling code here:
        int row = jCusTable.getSelectedRow();
        jTextCusID.setText(jCusTable.getValueAt(row, 0).toString());
        jTextCusName.setText(jCusTable.getValueAt(row, 1).toString());
        jFormattedTextCusSSN.setText(jCusTable.getValueAt(row, 2).toString());
        try {
            String dateString = jCusTable.getValueAt(row, 3).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng ngày
            Date date = dateFormat.parse(dateString); // Chuyển đổi chuỗi thành Date
            jDateCusdate.setDate(date); // Set vào JDateChooser
        } catch (ParseException e) {
            e.printStackTrace(); // Hiển thị lỗi ra console
        }
        jComboCusGender.setSelectedItem(jCusTable.getValueAt(row, 4).toString());
        jFormattedTextPhone.setText(jCusTable.getValueAt(row, 5).toString());
        jTextCusEmail.setText(jCusTable.getValueAt(row, 6).toString());
        jComboAddress.setSelectedItem(jCusTable.getValueAt(row, 7).toString());
    }//GEN-LAST:event_jCusTableMouseClicked

    private void FINDCUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FINDCUSMouseClicked
        // TODO add your handling code here:
        String cusID = jTextCusID.getText();
        Customer cus = customerService.findById(cusID);
        jTextCusID.setText(cus.getId());
        jTextCusName.setText(cus.getName());
        jFormattedTextCusSSN.setText(cus.getSSN());
        try {
            LocalDate localDate = cus.getBirthDate(); // Lấy LocalDate từ đối tượng Customer
            Date date = java.sql.Date.valueOf(localDate); // Chuyển LocalDate thành Date
            jDateCusdate.setDate(date); // Set vào JDateChooser
        } catch (Exception e) {
            e.printStackTrace();
        }
// Hiển thị lỗi ra console

        jComboCusGender.setSelectedItem(cus.getGender());
        jFormattedTextPhone.setText(cus.getPhoneNumber());
        jTextCusEmail.setText(cus.getEmail());
        jComboAddress.setSelectedItem(cus.getAddress());

    }//GEN-LAST:event_FINDCUSMouseClicked

    private void EDITCUSMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITCUSMouseClicked

    }//GEN-LAST:event_EDITCUSMouseClicked

    private void EDITCUSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITCUSMousePressed
        // TODO add your handling code here:
        String cusID = jTextCusID.getText().trim();
        if (cusID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Customer ID not blank!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Customer cus = customerService.findById(cusID);
        if (cus == null) {
            JOptionPane.showMessageDialog(null, "Customer is not valid!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Lấy thông tin từ giao diện
        String CusName = jTextCusName.getText().trim();
        String CusSSN = jFormattedTextCusSSN.getText().trim();
        String birthDateStr = null;

        Date selectedDate = jDateCusdate.getDate(); // Lấy ngày từ JDateChooser

        if (selectedDate != null) {
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng mong muốn
            birthDateStr = dateFormat.format(selectedDate);
        } else {
            JOptionPane.showMessageDialog(null, "You have not selected a date of birth!", "Error", JOptionPane.ERROR_MESSAGE);
        }
        String gender = jComboCusGender.getSelectedItem().toString();
        String Phone = jFormattedTextPhone.getText().trim();
        String Email = jTextCusEmail.getText().trim();
        String Address = (String) jComboAddress.getSelectedItem();

        // Kiểm tra dữ liệu đầu vào
        if (CusName.isEmpty() || CusSSN.isEmpty() || birthDateStr.isEmpty() || gender.isEmpty() || Phone.isEmpty() || Email.isEmpty() || Address.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter complete customer information!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Tạo đối tượng Customer để cập nhật
        Customer cusUpdate = new Customer(cusID, CusName, CusSSN, LocalDate.parse(birthDateStr), gender, Phone, Email, Address);

        try {
            // Gọi phương thức update từ CustomerService
            customerService.update(cusUpdate);
            displayCus();
            JOptionPane.showMessageDialog(null, "Customer information updated successfully!", "Notification", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating customer information: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        }
    }//GEN-LAST:event_EDITCUSMousePressed

    private void DELETECUSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DELETECUSMousePressed
        // TODO add your handling code here:
        String cusID = jTextCusID.getText().trim();
        if (cusID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Customer ID cannot be blank!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            // Gọi phương thức update từ CustomerService
            customerService.delete(cusID);
            displayCus();
            JOptionPane.showMessageDialog(null, "Customer deleted successfully!", "Notification", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating customer information: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        }

    }//GEN-LAST:event_DELETECUSMousePressed

    private void FINDCUSMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FINDCUSMousePressed
        // TODO add your handling code here:
        String cusID = jTextCusID.getText().trim();
        Customer cus = customerService.findById(cusID);
        if (cusID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Customer ID cannot be blank!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (cus == null) {
            JOptionPane.showMessageDialog(null, "Invalid Book", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            jTextCusID.setText(cus.getId());
            jTextCusName.setText(cus.getName());
            jFormattedTextCusSSN.setText(cus.getSSN());
            try {
                String dateString = cus.getBirthDate().toString();
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd"); // Định dạng ngày
                Date date = dateFormat.parse(dateString); // Chuyển đổi chuỗi thành Date
                jDateCusdate.setDate(date); // Set vào JDateChooser
            } catch (ParseException e) {
                e.printStackTrace(); // Hiển thị lỗi ra console
            }
            jComboCusGender.setSelectedItem(cus.getGender());
            jFormattedTextPhone.setText(cus.getPhoneNumber());
            jTextCusEmail.setText(cus.getEmail());
            jComboAddress.setSelectedItem(cus.getAddress());
        }
    }//GEN-LAST:event_FINDCUSMousePressed

    private void jTextIsBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIsBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIsBNActionPerformed

    private void jButtonAddBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAddBookMousePressed
        // TODO add your handling code here:
        try {
            // Lấy dữ liệu từ các JTextField
            String bookID = bookSer.increaseBOOKID();
            jTextBookID.setText(bookID);
            String title = JTitle.getText();
            String author = jTextAuthor.getText();
            String isbn = jTextIsBN.getText();
            String publishDateStr = jTextPublishDate.getText();
            String type = jType.getText();
            String price = jPrice.getText();
            int quantity = (int) ValueQuantity.getValue();
            String language = jCombolanguage.getSelectedItem().toString();
            double bookPrice = Double.parseDouble(price);
            Book existingBook = bookSer.findById(bookID);
            if (existingBook != null) {
                JOptionPane.showMessageDialog(null, "Error: Book code already exists!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            //          String bookId, String isbn, String title, String author, String publisher, String publishedDate, double price, int quantity, String type, String language
            Book book = new Book(bookID, isbn, title, author, "null", publishDateStr, bookPrice, quantity, type, language);

            // Gọi service để thêm sách
            boolean success = bookSer.insert1(book);

            // Kiểm tra kết quả
            if (success) {
                JOptionPane.showMessageDialog(null, "Added book successfully!");
                displayBook();
            } else {
                JOptionPane.showMessageDialog(null, "Error adding book!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: Invalid book price!", "Input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "An error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonAddBookMousePressed

    private void jButtonFindBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonFindBookMousePressed
        // TODO add your handling code here:

        try {
            String bookID = jTextBookID.getText();

            if (bookID.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Book ID cannot be blank!", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Book bk = bookSer.findById(bookID);

            if (bk == null) {
                JOptionPane.showMessageDialog(null, "Invalid Book", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }

            JTitle.setText(bk.getTitle());
            jTextAuthor.setText(bk.getAuthor());
            jTextIsBN.setText(bk.getIsbn());
            jTextPublishDate.setText(bk.getPublishedDate());
            jType.setText(bk.getType());
            jPrice.setText(String.valueOf(bk.getPrice())); // Chuyển số thành chuỗi nếu cần
            ValueQuantity.setValue(bk.getQuantity()); // Giữ nguyên nếu là JSpinner
            jCombolanguage.setSelectedItem(bk.getLanguage()); // Đặt giá trị cho JComboBox

        } catch (Exception e) {
            e.printStackTrace(); // In lỗi ra console để debug
            JOptionPane.showMessageDialog(null, "Error while searching for book: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonFindBookMousePressed

    private void jButtonDeleteBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonDeleteBookMousePressed
        String bookID = jTextBookID.getText().trim();
        if (bookID.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Book ID cannot be blank!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int confirm = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Customer?",
                "Confirm", JOptionPane.YES_NO_OPTION);
        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }
        try {
            // Gọi phương thức update từ CustomerService

            bookSer.delete(bookID);
            displayBook();
            JOptionPane.showMessageDialog(null, "Book deleted successfully!", "Notification", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating book information: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();

        }


    }//GEN-LAST:event_jButtonDeleteBookMousePressed

    private void EmployeeInfoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EmployeeInfoMousePressed
        emIn.setVisible(true);


    }//GEN-LAST:event_EmployeeInfoMousePressed

    private void jButtonEditBookMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditBookMousePressed
        try {
            // Lấy dữ liệu từ các JTextField
            String bookID = jTextBookID.getText();
            String title = JTitle.getText();
            String author = jTextAuthor.getText();
            String isbn = jTextIsBN.getText();
            String publishDateStr = jTextPublishDate.getText();
            String type = jType.getText();
            String price = jPrice.getText();
            int quantity = (int) ValueQuantity.getValue();
            String language = jCombolanguage.getSelectedItem().toString();
            double bookPrice = Double.parseDouble(price);

            //          String bookId, String isbn, String title, String author, String publisher, String publishedDate, double price, int quantity, String type, String language
            Book book = new Book(bookID, isbn, title, author, "null", publishDateStr, bookPrice, quantity, type, language);

            // Gọi service để thêm sách
            bookSer.update(book);
            displayBook();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Lỗi: Giá sách không hợp lệ!", "Lỗi nhập liệu", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Đã xảy ra lỗi: " + e.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_jButtonEditBookMousePressed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DELETECUS;
    private javax.swing.JButton EDITCUS;
    private javax.swing.JLabel EmployeeInfo;
    private javax.swing.JButton FINDCUS;
    private javax.swing.JTable JBookTable;
    private javax.swing.JTextField JTitle;
    private javax.swing.JSpinner ValueQuantity;
    private javax.swing.JButton jButtonAddBook;
    private javax.swing.JButton jButtonDeleteBook;
    private javax.swing.JButton jButtonEditBook;
    private javax.swing.JButton jButtonFindBook;
    private javax.swing.JComboBox<String> jComboAddress;
    private javax.swing.JComboBox<String> jComboCusGender;
    private javax.swing.JComboBox<String> jCombolanguage;
    private javax.swing.JTable jCusTable;
    private com.toedter.calendar.JDateChooser jDateCusdate;
    private javax.swing.JFormattedTextField jFormattedTextCusSSN;
    private javax.swing.JFormattedTextField jFormattedTextPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jPrice;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextAuthor;
    private javax.swing.JTextField jTextBookID;
    private javax.swing.JTextField jTextCusEmail;
    private javax.swing.JTextField jTextCusID;
    private javax.swing.JTextField jTextCusName;
    private javax.swing.JTextField jTextIsBN;
    private javax.swing.JTextField jTextPublishDate;
    private javax.swing.JTextField jType;
    // End of variables declaration//GEN-END:variables

}
